### ISSUE TITLE
bs.to api-key Änderung

### ISSUE THREAD

**Issue by Collabsvito** [lastship/EINGESTELLT-script.module.lastship-Module-2-2#31]
**Leider hat bs.to seit dem 11.05.2018 den api-key zu Ihrer Seite für die Neuentwicklung der Adroid-App geändert.**
siehe hierzu: [https://board.bs.to/index.php?/topic/1975-testphase-der-neuen-bsto-app/](url)
Kommentar auf der bs.to-Seite: 
> News
> BS.to App 12.05.18
> Wie ihr vermutlich mitbekommen habt, arbeiten wir an einer neuen App für BS.to. Dafür ist es gerade notwendig, dass im Hintergrund einiges geändert wird und dadurch resultierend die alte App nicht mehr funktioniert.
> Wir bitten dies zu entschuldigen!
> Wir haben im Forum bereits die Beta-Version der neuen App veröffentlicht die ihr ausgiebig testen könnt!

Daher verlaufen Anfragen mit dem alten api-key ins Nirwana und es kommt die Meldung "unauthorized".
Es wäre schön, wenn ein Fix möglich wäre und somit auch die Hoster von BS bei den Serien in **LASTSHIP** wieder auftauchen!
DANKE

**Comment by lastship** [comment]
Das kann leider noch lange dauern. Wir müssen mit dem Betreiber über einen neuen API key verhandeln, den ohne API Key sind jetzt bei BS.to zusätzlich Captcha vorgeschaltet, die sich bisher in Kodi nicht lösen lassen

**Comment by MartinX3** [comment]
Mit dem aktuellen Update gibt's wieder bs.to, allerdings mit captcha.

Mein Problem ist folgendes:
Ich scanne von KODI/lastship auf meinem RaspberryPi den CaptchaQR code ein, lande auf der Lastshop Homepage und bekomme ein "permission denied".
Ist das so geplant?
Dann müsste ich einen account für die lastship homepage anlegen und diesen im Handy abspeichern.

**Comment by sraedler** [comment]
@MartinX3 hab den qr code geändert.
Du hast übrigens die falsche Repo erwischt

**Comment by MartinX3** [comment]
Zugriff verweigert

Der Zutritt zu dieser Seite ist Ihnen leider verwehrt. Sie besitzen nicht die notwendigen Zugriffsrechte, um diese Seite aufrufen zu können.


Benötige ich ein Update für diese Änderung?

**Comment by sraedler** [comment]
Nightly Update machen...

Wenn das neue scannst kommst du dann hier raus:

https://lastship.github.io/Recaptcha.html
